[name]
[url]
-
[base]
-
[components]


couchbase
https://github.com/couchbase/docker/blob/0c5b1bde0c603d8f507964cc4e6a73f3cb6b39f3/community/couchbase-server/6.0.0/Dockerfile
-
FROM ubuntu:16.04
-
runit
wget
python-httplib2
chrpath
tzdata
lsof
lshw
sysstat
net-tools
numactl

python
https://github.com/docker-library/python/blob/fc2b02ab98f1d24e149758b05273d5f712a8946e/3.8-rc/stretch/Dockerfile
-
FROM buildpack-deps:stretch
-
tk-dev
uuid-dev
[direct-install]

mongo
https://github.com/docker-library/mongo/blob/135be00ece480b72826d871f5725214c35a1a9ab/3.4/Dockerfile
-
FROM debian:jessie-slim
-
ca-certificates
jq
numactl
wget
gnupg 
dirmngr
[direct-install]


docker-nginx
https://github.com/nginxinc/docker-nginx/blob/7890fc2342613e6669ad83ceead9c81136d2cc0a/mainline/stretch/Dockerfile
-
FROM debian:stretch-slim
-
gnupg1 
apt-transport-https 
ca-certificates
gettext-base
[direct-install]

debian
https://github.com/debuerreotype/docker-debian-artifacts/blob/3e751c2c2f60037e9231ed94bbd1f95347af2c87/buster/Dockerfile
-
None
-
[add tar to rootfs]

centos
https://github.com/CentOS/sig-cloud-instance-images/blob/9a389e11460bd809bb83c5fd4f095dbc8398d8cc/docker/Dockerfile
-
None
-
[add tar to rootfs]


mariadb
https://github.com/docker-library/mariadb/blob/93f1e9c9082364522c77b94e98299d7d398089f8/10.4/Dockerfile
-
FROM ubuntu:bionic
-
gnupg
ca-certificates
wget
apt-transport-https 
ca-certificates 
pwgen 
tzdata 
socat
[direct-install]

docker
https://github.com/docker-library/docker/blob/7411f18388ff3cc475f8b866cd2561f6b7822541/18.09/Dockerfile
-
FROM alpine:3.9
-
ca-certificates
[direct-install]

consul
https://github.com/hashicorp/docker-consul/blob/aff32e3913d64776d3776bf3086d4d5f5be3d95e/0.X/Dockerfile
-
FROM alpine:3.7
-
ca-certificates 
curl 
dumb-init 
gnupg 
libcap 
openssl 
su-exec 
iputils 
jq
[direct-install]

openjdk
https://github.com/docker-library/openjdk/blob/1aeda8a947bb0c1ae64c119972635cf6bcc64025/13/jdk/oracle/Dockerfile
-
FROM oraclelinux:7-slim
-
gzip
tar
freetype 
fontconfig
[direct-install]

php
https://github.com/docker-library/php/blob/bb16de8a711d1ba1dc76adf4665b3b1c06a06922/7.3/stretch/cli/Dockerfile
-
FROM debian:stretch-slim
-
autoconf 
dpkg-dev 
file 
g++ 
gcc
libc-dev
make 
pkg-config 
re2c
ca-certificates 
curl 
xz-utils 
dirmngr
gnupg
libcurl4-openssl-dev 
libedit-dev 
libsodium-dev 
libsqlite3-dev 
libssl-dev 
libxml2-dev 
zlib1g-dev 
libargon2-dev
[direct-install]



registry
https://github.com/docker/distribution-library-image/blob/0b6ea3ba50b65563600a717f07db4cfa6f18f957/amd64/Dockerfile
-
FROM alpine:3.8
-
ca-certificates 
apache2-utils
[direct-install]

golang
https://github.com/docker-library/golang/blob/fd272b2b72db82a0bd516ce3d09bba624651516c/1.12/stretch/Dockerfile
-
FROM buildpack-deps:stretch-scm
-
g++ 
gcc 
libc6-dev 
make 
pkg-config
[direct-install]














