#!/bin/bash    
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh
sudo docker run -d alpine sh